# Generated by Django 2.1.5 on 2019-04-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('import_country', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('sold_by', models.CharField(max_length=80)),
                ('sale_price', models.IntegerField()),
            ],
        ),
    ]
